# Generated by Django 5.2.7 on 2025-10-17 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aduan', models.CharField(max_length=200, verbose_name='Judul Pengaduan')),
                ('isi', models.TextField(verbose_name='Isi Pengaduan')),
                ('status', models.CharField(choices=[('BARU', 'Baru'), ('PROSES', 'Dalam Proses'), ('SELESAI', 'Selesai')], default='BARU', max_length=10, verbose_name='Status Pengaduan')),
                ('tanggal_aduan', models.DateTimeField(auto_now_add=True)),
                ('pelapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengaduan', to='warga.warga', verbose_name='Pelapor')),
            ],
        ),
    ]
